import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Menu from "../components/menu";
import Button from "../components/button";
import { LinkIcon, TrashIcon } from "@heroicons/react/24/solid";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />

      {/* header */}
      <div className="flex flex-col place-items-center p-44 y-3">
        <h1 className="text-5xl font-bold">Ayo Mulai Voting</h1>
        <h2 className="text-lg bg-zinc-100 px-3 py-1">
          Web Voting No.1 Di Indonesia
        </h2>
        <Image
          src={"/assets/header.svg"}
          alt={"header"}
          width={274}
          height={243}
        />
        <div className="space-x-10 flex">
          <Button
            text="Buat Vote Baru"
            className="font-bold"
            onClick={() => router.push("/vote/create")}
          />
          <Button
            text="Ikutan Vote"
            type="secondary"
            className="font-bold"
            onClick={() => router.push("/partisipant")}
          />
        </div>
      </div>
      {/* end */}
      {/* table */}
      <div>
        <p className="py-5 text-lg font-bold">Vote yang saya buat</p>
        <table className="table-auto w-full border border-zinc-100">
          <thead>
            <tr>
              <th>No</th>
              <th>Judul</th>
              <th>kandidat</th>
              <th>Kode</th>
              <th>Mulai</th>
              <th>Selesai</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className="p-5 text-left">1</td>
              <td className="p-5 text-left">Judul Voting</td>
              <td className="p-5 text-left">Budi vs Anto</td>
              <td className="p-5 text-left">BXAZIURH</td>
              <td className="p-5 text-left">20-08-2022</td>
              <td className="p-5 text-left">22-08-2022</td>
              <td className="p-5 text-left">
                <div>
                  <a href="#">
                    <LinkIcon className="w-8 h-8 p-2 hover:bg-zinc-100" />
                  </a>
                  <a href="#">
                    <TrashIcon className="w-8 h-8 p-2 hover:bg-zinc-100" />
                  </a>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      {/* end */}
    </div>
  );
};

export default Home;
